# Site settings
title:
email:
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username: Tooli_Inc
facebook_username: MyTooli
instagram_username: tooli.inc

# Build settings
markdown: kramdown
